Implement 4 missing API endpoints
Bynder/bynder-php-sdk pull request #68
Opened 2024-01-24 23:33 UTC by ConstantBqt

Create 5 new function to use missing endpoints 
- createMetaPropertyOption 
- modifyMetaPropertyOption
- getSingleMetaPropertyOptions
- syncAssetUsage
- getAccount

Update Request handler to fix an issue with json requests (Sync asset usage)

2024-01-25 13:37 UTC, dylanmartins approved these changes

2024-01-25 13:40 UTC, dylanmartins requested changes
@ConstantBqt Hey I see that the coverage decreased a bit, could you create some tests to cover these new calls?

Thanks!

2024-03-21 22:27 UTC, ConstantBqt commented
> @ConstantBqt sorry for the late answer, did you push the commit with the tests?

My bad, I didn't push it 😅  
Thanks

2024-07-23 17:19 UTC, ConstantBqt commented
> @ConstantBqt sorry for the late answer, did you push the commit with the tests?

Hi @dylanmartins, 
I have updated the code with the tests. Is there anything else I can do ? 
Thanks

2025-02-11 21:20 UTC, nyroDev commented on src/Bynder/Api/Impl/PermanentTokens/RequestHandler.php
> +        $headers = array_filter($options, function ($key) {
I did the same kind of filter for `form_params` in #65 
I guess there might be other key to remove here too..

2025-03-25 15:46 UTC, ConstantBqt commented
Hi, I rebased the branch and removed the duplicated endpoint.

2025-03-25 18:08 UTC, ahongbynder approved these changes

2025-03-25 18:10 UTC, merged